canonical/prompting-client

.tool-versions, flutter_packages/prompting_client/pubspec.yaml, flutter_packages/prompting_client_ui/linux/flutter/generated_plugin_registrant.cc, flutter_packages/prompting_client_ui/linux/flutter/generated_plugins.cmake, flutter_packages/prompting_client_ui/linux/my_application.cc, flutter_packages/prompting_client_ui/pubspec.lock, flutter_packages/prompting_client_ui/pubspec.yaml, melos.yaml
Downgrades Flutter to 3.19.6 to avoid rendering issues still present in 3.24.1 and adds `handy_window` (rounded corners) for visual consistency
Note:
The `handy_window` plugin seems to have some conflicts with the `yaru_window` plugin, which prevents us from using `YaruWindow.onClose`. This means we'll need to handle the case in which the user closes the dialog in the rust client.
=> feat(prompting_ui): add libhandy for rounded corners

flutter_packages/prompting_client/lib/src/generated/apparmor-prompting.pbenum.dart, flutter_packages/prompting_client/lib/src/generated/apparmor-prompting.pbjson.dart, flutter_packages/prompting_client/lib/src/prompting_client.dart, flutter_packages/prompting_client/lib/src/prompting_models.dart, flutter_packages/prompting_client/test/prompting_client_test.dart, flutter_packages/prompting_client_ui/lib/l10n/app_en.arb, flutter_packages/prompting_client_ui/lib/l10n_x.dart, prompting-client/src/daemon/server.rs, prompting-client/src/protos/apparmor_prompting.rs, prompting-client/src/snapd_client/interfaces/home.rs, protos/apparmor-prompting.proto
The new variant isn't in use yet but I'm updating the Rust client next to include it in the generated options for subfolder paths. I missed updating the conversion method for `PromptReplyResponse` in a previous change and nearly did the same thing again here with `HomePatternType` so I've added some very simple regression tests that just iterate over the protobuf enum variants and check to see if anything throws when it gets run through the conversion method. If there's a more idiomatic way to handle this sort of check then please let me know and I'll move us over to that instead :smile: 
> For context, I don't _think_ we can simply rely on the match being marked as non-exhaustive as we are using generated "enum-_like_" classes with an explicit list of variants rather than true enums. If …
=> feat: adding new home pattern type to the GRPC API

flutter_packages/prompting_client_ui/lib/home/home_prompt_data_model.dart, flutter_packages/prompting_client_ui/lib/home/home_prompt_page.dart, flutter_packages/prompting_client_ui/test/home/home_prompt_page_test.dart, melos.yaml, prompting-client/src/snapd_client/mod.rs
https://github.com/canonical/snapd/pull/14473 addresses the underlying cause of the "About this app" section ending up without any data to display (the rework of the prompting interface included trimming down the permissions it granted so we lost access to `/v2/snaps/$name`). From our side we also need to make sure that if the app metadata is not available, we no longer render the section in the prompt (see the screenshot below).
I've updated the tests in the UI to ensure that we don't render the "About this app" section when meta data is missing as a regression test for this.
> @juanruitina "Custom path pattern" is still there because I've not started work on the UI fixes yet I'm afraid.
This PR also fixes the melos targets we have so that they correctly use `fvm` now that we are relying …
=> fix: only show the about this app section when metadata is available

flutter_packages/prompting_client_ui/lib/prompt_page.dart
This workaround fixes an issue presumably caused by a race condition during the initialization of the GTK window and the flutter view within that window.
=> fix(prompting_ui): ensure the window is resized correctly

flutter_packages/prompting_client_ui/integration_test/apparmor_prompt_test.dart, flutter_packages/prompting_client_ui/lib/home/home_prompt_data_model.dart, flutter_packages/prompting_client_ui/lib/home/home_prompt_page.dart, flutter_packages/prompting_client_ui/lib/l10n/app_en.arb, flutter_packages/prompting_client_ui/lib/l10n_x.dart, flutter_packages/prompting_client_ui/lib/test_prompt_details.json, flutter_packages/prompting_client_ui/lib/widgets/form_widgets.dart, flutter_packages/prompting_client_ui/test/home/home_prompt_page_test.dart
This is tracked internally by https://warthogs.atlassian.net/browse/UDENG-4402
=> fix: small UI fixes

flutter_packages/prompting_client_ui/test/home/home_prompt_page_test.dart, flutter_packages/prompting_client_ui/test/l10n_x_test.dart
Generalizes the 'display prompt details' test to include all currently supported cases. So far it only asserts that:
* the options marked as `showInitially` are, in fact, shown initally
* all options are shown after pressing 'more options'
* the corresponding path patterns are displayed alongside the option titles
There's a separate test that verifies the l10n strings are created correctly (in particular for top level folders and matching file extensions).
UDENG-4478
=> test: add UI tests for all supported cases

.github/workflows/publish-integration-tests.yaml
@olivercalder I think this should do the trick? If it works as intended then the APIs described here should work for locating and downloading the artifact: https://docs.github.com/en/rest/actions/artifacts?apiVersion=2022-11-28
=> chore: publish the integration tests binary for snapd

flutter_packages/prompting_client_ui/lib/home/home_prompt_page.dart, flutter_packages/prompting_client_ui/lib/l10n/app_en.arb, flutter_packages/prompting_client_ui/test/home/home_prompt_page_test.dart
Adds an 'allow once' button and de-emphasizes the 'more options' button in accordance with the updated Figma designs.
I've also made sure the buttons overflow into the next line in case there isn't enough horizontal space (which might happen for some languages)
UDENG-4494
=> feat(prompting_ui): add 'allow once' button, demote 'more options'

prompting-client/Cargo.toml, prompting-client/build.rs, prompting-client/src/bin/daemon.rs, prompting-client/src/bin/set_log_level.rs, prompting-client/src/cli_actions/log_level.rs, prompting-client/src/cli_actions/mod.rs, prompting-client/src/daemon/mod.rs, prompting-client/src/daemon/server.rs, prompting-client/src/lib.rs, prompting-client/src/protos/apparmor_prompting.rs, prompting-client/tests/integration.rs, protos/apparmor-prompting.proto, snap/snapcraft.yaml
This lets us do the following:
```bash
$ prompting-client.logging-level --filter=debug
```
and have the daemon update its logging filter without needing to restart the service. By default we will now log at info level.
=> feat(daemon): support dynamically setting the logging level at runtime

prompting-client/src/bin/daemon.rs, prompting-client/src/bin/echo.rs, prompting-client/src/bin/scripted.rs, prompting-client/src/cli_actions/scripted.rs, prompting-client/src/daemon/poll.rs, prompting-client/src/daemon/server.rs, prompting-client/src/lib.rs, prompting-client/src/snapd_client/mod.rs, prompting-client/tests/integration.rs
- update our handling of snapd errors to make use of consistent error codes
- factor out repeated logic around checking if prompting is enabled
- exit so systemd restarts us if we hit permission denied in the poll loop
- retry with limited attempts and a sleep if we hit other errors in the poll loop
=> fix(daemon): exiting if we get permission denied on notices long poll

docs/running-the-scripted-client.md, prompting-client/resources/prompt-sequence-tests/e2e_erroring_write_test.json, prompting-client/resources/prompt-sequence-tests/e2e_unexpected_additional_prompt_test.json, prompting-client/resources/prompt-sequence-tests/e2e_write_test.json, prompting-client/resources/prompt-sequence-tests/e2e_wrong_path_test.json, prompting-client/resources/prompt-sequence-tests/sequence_with_top_level_filter_and_vars.json, prompting-client/resources/scripted-tests/happy-path-read/prompt-sequence.json, prompting-client/resources/scripted-tests/happy-path-read/test.sh, prompting-client/src/bin/scripted.rs, prompting-client/src/cli_actions/mod.rs, prompting-client/src/cli_actions/scripted.rs, prompting-client/src/lib.rs, prompting-client/src/prompt_sequence.rs, prompting-client/tests/integration.rs
- Support specifying a top level filter to limit what prompts the sequence attempts to match against
- Support specifying and using variables to allow for passing per-run specific data (e.g. a temp directory)
See the updated sequence JSON files for examples of how this looks in practice.
A full example "spread" test for a happy path read can be written as follows:
```bash
#!/usr/bin/env sh
PREFIX="$1"
TEST_DIR="/home/ubuntu/test/$PREFIX"
prompting-client.scripted \
--script="$TEST_DIR/prompt-sequence.json" \
--var "BASE_PATH:$TEST_DIR" | tee "$TEST_DIR/outfile" &
sleep 0.2
TEST_OUTPUT="$(aa-prompting-test.read "$PREFIX")"
sleep 0.2
CLIENT_OUTPUT="$(cat "$TEST_DIR/outfile")"
if [ "$CLIENT_OUTPUT" != "success" ]; then
echo "test failed"
echo "output='$CLIENT_OUTPUT'"
exit 1
fi
if [ …
```
=> feat(scripted-client): supporting passing templating variables and a top level filter

prompting-client/src/daemon/worker.rs, prompting-client/src/lib.rs, prompting-client/src/recording.rs, prompting-client/src/snapd_client/interfaces/home.rs, prompting-client/src/snapd_client/interfaces/mod.rs, prompting-client/src/snapd_client/prompt.rs
The helper methods used for determining which category of path we are generating options for implicitly assumes that the user’s home directory is located in /home. This has the potential to generate invalid options or possibly hard error in the generation of options if the user has set their home directory to be somewhere else.
We now take the value of `$SNAP_REAL_HOME` into account when generating the options rather than assuming the standard home directory location.
I've also tidied up the method that generates the options to make it easier to read exactly which options will be provided in each of the cases outlined in @juanruitina's Figma design.
---
One interesting side effect of sorting this out is that it has highlighted that we have a very odd (but I think technically possible?) …
=> fix(prompting-client): fix home pattern generation when home is not under /home

flutter_packages/prompting_client_ui/lib/home/home_prompt_data_model.dart, flutter_packages/prompting_client_ui/test/home/home_prompt_page_test.dart
Currently the UI expects the grpc server to only reply with an error status when sending a reply with a custom path pattern, so the corresponding error message is displayed as a validation string for the text field.
However, it is possible that we receive errors for simpler replies as well, and we should display those properly in the UI. As a workaround, this PR simply ensures that the 'custom path' option gets selected and the text field is revealed, if the server returns an error.
[Screencast from 2024-09-20 12-39-55.webm](https://github.com/user-attachments/assets/3ae6edb7-2af1-44bf-8c18-6522065825aa)
=> feat: reveal custom path text field on error

flutter_packages/prompting_client_ui/lib/prompt_page.dart
Fixes a bug where the prompt window flickers due to multiple successive resizes caused by overflowing widgets when the (horizontally expanding) metadata dropdown is missing:
Before:
[Screencast from 2024-09-20 15-26-41.webm](https://github.com/user-attachments/assets/6d83c115-63a0-4169-be20-954770334337)
After:
[Screencast from 2024-09-20 15-27-08.webm](https://github.com/user-attachments/assets/2f0aec51-2a0c-4fe9-9664-d81887a4a71b)
=> fix: set minimum window width

flutter_packages/prompting_client_ui/lib/home/home_prompt_page.dart, flutter_packages/prompting_client_ui/lib/main.dart, flutter_packages/prompting_client_ui/lib/theme.dart
Reduces the text sizes of the radio/checkbox titles and the custom path text field as suggested by @juanruitina.
UDENG-4608
=> feat: use `bodyMedium` font size for titles

prompting-client/src/cli_actions/scripted.rs, prompting-client/src/daemon/poll.rs, prompting-client/src/daemon/worker.rs, prompting-client/src/snapd_client/mod.rs, prompting-client/src/snapd_client/prompt.rs, prompting-client/tests/integration.rs
The data we get from the snapd notices endpoint now supports an optional `last-data` field which we can use to be a little more efficient in how we pull prompt details.
```
{
"id": "1674",
"user-id": 1000,
"type": "interfaces-requests-prompt",
"key": "000000000000014E",
"first-occurred": "2024-09-13T13:05:05.189006863Z",
"last-occurred": "2024-09-13T13:05:05.232809028Z",
"last-repeated": "2024-09-13T13:05:05.232809028Z",
"occurrences": 2,
"last-data": {
"resolved": "replied"
},
"expire-after": "168h0m0s"
}
```
In the case where we get a notice with `last-data.resolved == "replied"` we can treat this in the same way we currently treat getting a 404 when pulling prompt details (i.e. removing our internal state for that prompt).
=> feat: checking for last-data in notices from snapd

docs/running-the-scripted-client.md, prompting-client/resources/prompt-sequence-tests/sequence_without_replies.json, prompting-client/src/cli_actions/scripted.rs, prompting-client/src/prompt_sequence.rs
Support not replying to every prompt in a scripted client prompt-sequence.
Currently, prompting-client.scripted accepts scripts which have a top-level "prompt-filter" and a "prompts" list, which is a list of json objects with two mandatory fields: "prompt-filter" and "reply". The scripted client expects relevant prompts to match the filters specified in the "prompts" list in order, and for each one, immediately sends back the accompanying reply.
However, to write a spread test which mimics the `create_multiple_actioned_by_other_pid` integration test, we need to be able to attempt multiple writes (and check that those attempts occurred as expected), and then on a subsequent attempt, reply with a rule which then actions the previous prompts as well.
The docs update and new test data cover …
=> feat: Scripted client nullable replies

CONTRIBUTING.md
I was over eager on merging https://github.com/canonical/prompting-client/pull/126 which had an outstanding question about the details on reporting security issues. We now point to the new SECURITY.md file rather than provided details in CONTRIBUTING.md
=> chore: pointing to SECURITY.md in CONTRIBUTING.md for security issues

prompting-client/src/daemon/mod.rs, prompting-client/src/daemon/poll.rs, prompting-client/src/daemon/server.rs, snap/snapcraft.yaml
Addresses the issue reported in https://github.com/canonical/desktop-security-center/issues/71
@olivercalder confirms that this removes the log spam when running in a VM without a desktop session but he's still seeing the following denial which I'm yet to track down:
```
Oct 10 16:13:26 integration-oracular kernel: audit: type=1400 audit(1728576806.803:30728): apparmor="DENIED" operation="open" class="file" profile="snap-update-ns.prompting-client" name="/proc/417652/maps" pid=417652 comm="5" requested_mask="r" denied_mask="r" fsuid=1000 ouid=0
```
I've also reduced multiple log lines from `INFO` to `DEBUG` so the prompting client is less chatty by default.
=> fix(daemon): set TOKIO_WORKER_THREADS to stop tokio trying to read cgroup files which will result in apparmor denials

flutter_packages/prompting_client_ui/lib/home/home_prompt_data_model.dart, flutter_packages/prompting_client_ui/lib/home/home_prompt_error.dart, flutter_packages/prompting_client_ui/lib/home/home_prompt_page.dart, flutter_packages/prompting_client_ui/lib/l10n/app_en.arb, flutter_packages/prompting_client_ui/lib/test_prompt_details.json, flutter_packages/prompting_client_ui/test/home/home_prompt_page_test.dart
Adds an error box to the prompting UI to display generic errors received from the rust client when submitting a reply.
The only error we currently handle explicitly is `PROMPT_NOT_FOUND`, in which case UI closes normally when the reply is submitted, without any indication to the user that the prompt has already been handled and their reply is ignored (we have this as an issue in our backlog to come back to).
For `UNKNOWN` errors, all we can currently do is show a generic message along with the raw error string, see screen recording. We've previously shown the raw error message only as part of the text field validation for the custom path pattern. Generally, we don't know whether the error is related to the custom path pattern, so in this generic case we should completely disentangle the …
=> feat(prompt_ui): add error message box

flutter/apps/prompting_client_ui/lib/l10n/app_en.arb, flutter/apps/prompting_client_ui/lib/pages/home/home_prompt_data_model.dart, flutter/apps/prompting_client_ui/lib/pages/home/home_prompt_page.dart, flutter/apps/prompting_client_ui/lib/test_prompt_details.json, flutter/apps/prompting_client_ui/pubspec.lock, flutter/apps/prompting_client_ui/test/home/home_prompt_page_test.dart, flutter/apps/prompting_client_ui/test/test_utils.dart, flutter/packages/prompting_client/lib/src/generated/apparmor-prompting.pb.dart, flutter/packages/prompting_client/lib/src/generated/apparmor-prompting.pbjson.dart, flutter/packages/prompting_client/lib/src/prompting_client.dart, flutter/packages/prompting_client/lib/src/prompting_models.dart, flutter/packages/prompting_client/test/prompting_client_test.dart, prompting-client/src/daemon/server.rs, prompting-client/src/protos/apparmor_prompting.rs, prompting-client/src/snapd_client/interfaces/home.rs, protos/apparmor-prompting.proto
Updates prompting messaging to align with MVP designs: https://www.figma.com/board/1DIGbaCf4ZjTcShYjLiAIi/24.10-AppArmor-prompting---MVP-logic?node-id=0-1&node-type=canvas&t=5IUl7Ys94lcOdA9J-0
Namely, messaging is now dependent on if a folder or file is being asked for, and where in relation to the users home directory it is. There are 5 variations we consider:
- Asking for permissions to the users Home directory
- Asking for permissions to a file within the Home directory
- Asking for permissions to a Folder in the home directory (a top level folder)
- Asking for permissions to a file with within a top level folder
- Asking for permissions to a folder or file nested more deeply than a top level folder
The type of path that is being requested, as well as relevant file and folder used in …
=> feat: path based prompting message

.github/workflows/tics.yaml, melos.yaml
This is now hooked up and "working" for a given definition of working (a green run can be found [here](https://github.com/canonical/prompting-client/actions/runs/13160779575)).
For some reason, TiCS is reporting that it can find coverage for some files in the project (such as `flutter/apps/prompting_client_ui/lib/l10n.dart`) but not others when they are contained in the same coverage file (such as `flutter/apps/prompting_client_ui/lib/l10n_x.dart`). From what I can see locally when generating the coverage I'd expect it to find neither or both, and all I can see that is different in the output from the workflow run is that the files which _are_ found have a `(recheck)` suffix to their relevant log lines.
Interestingly the files in the `flutter/packages` seem to be processed correctly so I …
=> chore: setting up TiCS CI integration

flutter/apps/prompting_client_ui/lib/main.dart
Adds the missing high contrast theme for the prompting UI
=> feat: add high contrast theme

docs/adding-support-for-new-interfaces.md, prompting-client/src/daemon/mod.rs, prompting-client/src/daemon/server.rs, prompting-client/src/daemon/worker.rs, prompting-client/src/lib.rs, prompting-client/src/snapd_client/interfaces/home.rs, prompting-client/src/snapd_client/interfaces/mod.rs, prompting-client/src/snapd_client/mod.rs, prompting-client/src/snapd_client/prompt.rs
We still had a couple of places outside of the `SnapInterface` trait that were specific to the current home interface support. None of the business logic is changing as part of this PR, but those interface specific pieces of logic have been moved out to live either in the trait itself or in associated helper types, so that adding support for a new interface doesn't need to touch other parts of the codebase.
Currently work in progress:
=> chore: pull out all interface specific logic into the SnapInterface trait

prompting-client/Cargo.toml, prompting-client/src/bin/daemon.rs, prompting-client/src/bin/echo.rs, prompting-client/src/bin/scripted.rs, prompting-client/src/snapd_client/mod.rs, prompting-client/tests/integration.rs
Added support for the upcoming snapd abstract snap socket:
- bumped `tokio` to 1.40, where support for abstract sockets was first introduced
- added check for abstract socket and a fall back to the current snapd socket
The `tokio` implementation of `UnixStream::connect` is `async`, so I also propagated that where appropriate. Unfortunately, the `Default` trait is synchronous, so I had to drop that in favor of having clients call `new().await` directly.
There is a way to call connect on abstract sockets via the [SocketAddrExt](https://doc.rust-lang.org/stable/std/os/linux/net/trait.SocketAddrExt.html), but its not as simple as calling `UnixStream::connet`, and I felt dropping the `Default` and making the `new` function async was simpler. Open to doing it the other way if we think …
=> Abstract snapd snap socket support

.github/workflows/tics.yaml
I've asked the tiobe team to change the coverage directory to `coverage` for consistency with our other repositories.
I've also removed the cobertura XML conversion for Dart, as TiCS seems to specifically look for Flutter's lcov output.
UDENG-5819
=> ci(tics): update coverage dir and remove XML conversion

flutter/apps/prompting_client_ui/integration_test/apparmor_prompt_test.dart, flutter/apps/prompting_client_ui/lib/fake_prompting_client.dart, flutter/apps/prompting_client_ui/lib/main.dart, flutter/apps/prompting_client_ui/pubspec.lock, flutter/apps/prompting_client_ui/test/test_utils.dart, flutter/packages/prompting_client/lib/src/generated/apparmor-prompting.pb.dart, flutter/packages/prompting_client/lib/src/generated/apparmor-prompting.pbenum.dart, flutter/packages/prompting_client/lib/src/generated/apparmor-prompting.pbgrpc.dart, flutter/packages/prompting_client/lib/src/generated/apparmor-prompting.pbjson.dart, flutter/packages/prompting_client/lib/src/generated/google/protobuf/empty.pb.dart, flutter/packages/prompting_client/lib/src/generated/google/protobuf/empty.pbenum.dart, flutter/packages/prompting_client/lib/src/generated/google/protobuf/empty.pbjson.dart, flutter/packages/prompting_client/lib/src/generated/google/protobuf/wrappers.pb.dart, flutter/packages/prompting_client/lib/src/generated/google/protobuf/wrappers.pbenum.dart, flutter/packages/prompting_client/lib/src/generated/google/protobuf/wrappers.pbjson.dart, flutter/packages/prompting_client/lib/src/prompting_client.dart, flutter/packages/prompting_client/pubspec.yaml, flutter/packages/prompting_client/test/prompting_client_test.dart, prompting-client/Cargo.lock, prompting-client/Cargo.toml, prompting-client/src/bin/daemon.rs, prompting-client/src/daemon/mod.rs, prompting-client/src/daemon/server.rs, prompting-client/src/daemon/worker.rs, prompting-client/src/lib.rs, prompting-client/src/protos/apparmor_prompting.rs, protos/apparmor-prompting.proto
This makes the prompting-client continue pulling and processing updates while a prompt is shown. If an update renders the active prompt obsolete the UI is automatically closed.
Key changes:
* `worker::step` doesn't block until the prompt UI subprocess terminates anymore, but instead listens for both prompt updates and the process termination in a `tokio::select!` statement.
* the gRPC server now returns a stream of `GetCurrentPromptResponse`s - closing the stream indicates to the UI that the prompt has been dropped and that the UI should quit.
~I'm still working on adjusting the tests and adding new ones.~
Internal spec: UD101
UDENG-7538
=> feat: prompt cancellation

flutter/apps/prompting_client_ui/lib/pages/home/home_prompt_page.dart, prompting-client/src/snapd_client/prompt.rs, prompting-client/tests/integration.rs
The `session` lifespan is now supported in snapd. This change simply uncomments the implementation on the prompting client side to expose the feature.
=> feat: uncomment session lifespan code now that it is supported in snapd

prompting-client/Cargo.toml, prompting-client/src/daemon/worker.rs, prompting-client/src/snapd_client/interfaces/mod.rs, prompting-client/src/snapd_client/mod.rs
Add `auto-reply` feature flag to support benchmarking automation.
The original implementation is on [autoreply-and-time-debugging](https://github.com/canonical/prompting-client/tree/autoreply-and-time-debugging) branch
---
UDENG-7913
=> feat: feature flagged `auto-reply` to prompt 

flutter/apps/prompting_client_ui/integration_test/apparmor_prompt_test.dart, flutter/apps/prompting_client_ui/lib/main.dart, flutter/apps/prompting_client_ui/linux/my_application.cc, prompting-client/src/daemon/worker.rs, snap/snapcraft.yaml
Added a dbus call to `com.canonical.Shell.PermissionPrompting`  in `my_application.cc` with the `snap_name` and `app_pid`, which are now expected as command line arguments to the Flutter application when launched from the `prompting_client`. 
This call is preformed before `gtk_widget_show` is called.
UDENG-7321
=> feat: implement GNOME Shell permission prompting functionality

prompting-client/src/daemon/poll.rs
This makes sure the prompting-client exits when the prompting feature is turned off.
=> feat: check if prompting is enabled on poll timeout
